// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// [control] The backend, e.g. "miniaudio/Core Audio" or "oboe/aaudio".
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudIoStream>)>()
external ffi.Pointer<ffi.Char> aud_io_backend_name(
  ffi.Pointer<AudIoStream> stream,
);

/// [control] The output channels.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_channels(ffi.Pointer<AudIoStream> stream);

/// [control] Closes the stream and the device.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudIoStream>)>()
external void aud_io_close(ffi.Pointer<AudIoStream> stream);

/// [control] The negotiated block size; 0 when the backend does not say.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_frames_per_callback(ffi.Pointer<AudIoStream> stream);

/// [control] Copies the counters.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<AudIoStream>, ffi.Pointer<AudIoStats>)
>()
external void aud_io_get_stats(
  ffi.Pointer<AudIoStream> stream,
  ffi.Pointer<AudIoStats> stats,
);

/// [control] Opens an output stream that calls `render` with `user` from the
/// audio thread. Returns NULL when the device cannot be opened.
@ffi.Native<
  ffi.Pointer<AudIoStream> Function(
    ffi.Pointer<AudIoConfig>,
    AudRenderCallback,
    ffi.Pointer<ffi.Void>,
  )
>()
external ffi.Pointer<AudIoStream> aud_io_open(
  ffi.Pointer<AudIoConfig> config,
  AudRenderCallback render,
  ffi.Pointer<ffi.Void> user,
);

/// [control] Zeroes the counters.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudIoStream>)>()
external void aud_io_reset_stats(ffi.Pointer<AudIoStream> stream);

/// [control] The sample rate the device runs at.
@ffi.Native<ffi.Double Function(ffi.Pointer<AudIoStream>)>()
external double aud_io_sample_rate(ffi.Pointer<AudIoStream> stream);

/// [realtime] A render callback that fills the output with a 440 Hz sine at
/// -20 dBFS, the smoke signal of this package; `user` is ignored.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external void aud_io_sine_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<ffi.Float> interleaved_output,
  int frames,
  int channels,
);

/// [control] Starts the callbacks; AUD_ERROR_STATE when already started.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_start(ffi.Pointer<AudIoStream> stream);

/// [control] Stops the callbacks and waits for the last one to return.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stop(ffi.Pointer<AudIoStream> stream);

/// How a stream is opened.
final class AudIoConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// 0 = the device's native rate
  @ffi.Double()
  external double sample_rate;

  /// output channels
  @ffi.Uint32()
  external int channels;

  /// 0 = the backend's default
  @ffi.Uint32()
  external int frames_per_callback;

  /// 1 = a silent device that keeps time (tests)
  @ffi.Int32()
  external int use_null_backend;

  static ffi.Pointer<AudIoConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required double sample_rate,
    required int channels,
    required int frames_per_callback,
    required int use_null_backend,
  }) => $allocator<AudIoConfig>()
    ..ref.struct_size = struct_size
    ..ref.sample_rate = sample_rate
    ..ref.channels = channels
    ..ref.frames_per_callback = frames_per_callback
    ..ref.use_null_backend = use_null_backend;
}

/// Counters the stream callback keeps; read with aud_io_get_stats.
final class AudIoStats extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// smallest callback block
  @ffi.Uint32()
  external int frames_min;

  /// largest callback block
  @ffi.Uint32()
  external int frames_max;

  @ffi.Uint64()
  external int callbacks;

  @ffi.Uint64()
  external int frames;

  /// time between callback starts
  @ffi.Int64()
  external int period_min_ns;

  @ffi.Int64()
  external int period_max_ns;

  @ffi.Int64()
  external int period_sum_ns;

  @ffi.Uint64()
  external int period_count;

  /// period above 1.5 times the block duration
  @ffi.Uint64()
  external int late_callbacks;

  /// reported by the backend; Oboe only
  @ffi.Uint64()
  external int xruns;

  /// the backend closed the stream (route change)
  @ffi.Uint64()
  external int disconnects;

  /// time spent inside the callback
  @ffi.Int64()
  external int callback_time_max_ns;

  @ffi.Int64()
  external int callback_time_sum_ns;

  /// reported by the backend; Oboe only, else 0
  @ffi.Double()
  external double output_latency_ms;

  static ffi.Pointer<AudIoStats> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int frames_min,
    required int frames_max,
    required int callbacks,
    required int frames,
    required int period_min_ns,
    required int period_max_ns,
    required int period_sum_ns,
    required int period_count,
    required int late_callbacks,
    required int xruns,
    required int disconnects,
    required int callback_time_max_ns,
    required int callback_time_sum_ns,
    required double output_latency_ms,
  }) => $allocator<AudIoStats>()
    ..ref.struct_size = struct_size
    ..ref.frames_min = frames_min
    ..ref.frames_max = frames_max
    ..ref.callbacks = callbacks
    ..ref.frames = frames
    ..ref.period_min_ns = period_min_ns
    ..ref.period_max_ns = period_max_ns
    ..ref.period_sum_ns = period_sum_ns
    ..ref.period_count = period_count
    ..ref.late_callbacks = late_callbacks
    ..ref.xruns = xruns
    ..ref.disconnects = disconnects
    ..ref.callback_time_max_ns = callback_time_max_ns
    ..ref.callback_time_sum_ns = callback_time_sum_ns
    ..ref.output_latency_ms = output_latency_ms;
}

final class AudIoStream extends ffi.Opaque {}

/// [realtime] The render interface between a host of the engine and the
/// engine (plugin-002): the host supplies an interleaved output buffer, the
/// engine fills `frames` frames of `channels` channels. aud_audio_io calls
/// it from its stream callback.
typedef AudRenderCallback =
    ffi.Pointer<ffi.NativeFunction<AudRenderCallbackFunction>>;
typedef AudRenderCallbackFunction =
    ffi.Void Function(
      ffi.Pointer<ffi.Void> user,
      ffi.Pointer<ffi.Float> interleaved_output,
      ffi.Uint32 frames,
      ffi.Uint32 channels,
    );
typedef DartAudRenderCallbackFunction =
    void Function(
      ffi.Pointer<ffi.Void> user,
      ffi.Pointer<ffi.Float> interleaved_output,
      int frames,
      int channels,
    );
