// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'package:aud_audio_core/aud_audio_core_bindings.dart' as core;
import 'dart:ffi' as ffi;

/// [control] Injects a fault into the null devices of the session.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudIoSession>, ffi.Uint32, ffi.Int64)
>()
external int aud_io_null_inject(
  ffi.Pointer<AudIoSession> session,
  int fault,
  int value,
);

/// [control] With AUD_IO_SESSION_MANUAL_CLOCK: runs one device callback of
/// the stream with interleaved `input` and `output` (either may be NULL) at
/// the host time `host_time_ns`; AUD_ERROR_STATE unless the stream runs.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudIoStream>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint32,
    ffi.Int64,
  )
>()
external int aud_io_null_process(
  ffi.Pointer<AudIoStream> stream,
  ffi.Pointer<ffi.Float> input,
  ffi.Pointer<ffi.Float> output,
  int frames,
  int host_time_ns,
);

/// [control] Lets the null devices of the session call back in the cycle of
/// `sizes` instead of their buffer size; 0 sizes restore it.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudIoSession>,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external int aud_io_null_set_block_sizes(
  ffi.Pointer<AudIoSession> session,
  ffi.Pointer<ffi.Uint32> sizes,
  int count,
);

/// [control] Creates a probe that clicks every `interval_frames` frames and
/// detects an onset above `threshold` (0 = 0.1); NULL for an interval of 0.
@ffi.Native<ffi.Pointer<AudIoProbe> Function(ffi.Uint32, ffi.Float)>()
external ffi.Pointer<AudIoProbe> aud_io_probe_create(
  int interval_frames,
  double threshold,
);

/// [control] Destroys a probe no stream renders with any more.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudIoProbe>)>()
external void aud_io_probe_destroy(ffi.Pointer<AudIoProbe> probe);

/// [control] Writes what the probe measured into `out`.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudIoProbe>, ffi.Pointer<AudIoProbeResult>)
>()
external int aud_io_probe_read(
  ffi.Pointer<AudIoProbe> probe,
  ffi.Pointer<AudIoProbeResult> out,
);

/// [realtime] Renders the probe in `user`, an AudIoProbe.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<core.AudRenderRequest>)
>()
external int aud_io_probe_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<core.AudRenderRequest> request,
);

/// [control] The name of the session's backend, e.g. "oboe" or "null".
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudIoSession>)>()
external ffi.Pointer<ffi.Char> aud_io_session_backend_name(
  ffi.Pointer<AudIoSession> session,
);

/// [control] Creates a session; NULL for an invalid configuration. On iOS the
/// session configures and activates the AVAudioSession.
@ffi.Native<
  ffi.Pointer<AudIoSession> Function(ffi.Pointer<AudIoSessionConfig>)
>()
external ffi.Pointer<AudIoSession> aud_io_session_create(
  ffi.Pointer<AudIoSessionConfig> config,
);

/// [control] Closes the remaining streams and destroys the session.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudIoSession>)>()
external void aud_io_session_destroy(ffi.Pointer<AudIoSession> session);

/// [control] Writes up to `capacity` devices into `out` and returns how many
/// exist; AUD_ERROR_UNSUPPORTED where the Dart side lists them (Android).
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudIoSession>,
    ffi.Pointer<AudIoDevice>,
    ffi.Uint32,
  )
>()
external int aud_io_session_devices(
  ffi.Pointer<AudIoSession> session,
  ffi.Pointer<AudIoDevice> out,
  int capacity,
);

/// [control] Tells the streams of the session that the system took the
/// audio, e.g. Android's audio focus went; running streams stop and report
/// AUD_IO_NOTIFY_INTERRUPTED.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoSession>, ffi.Uint32)>()
external int aud_io_session_interrupt(
  ffi.Pointer<AudIoSession> session,
  int reason,
);

/// [control] The microphone permission, an AUD_IO_PERMISSION_*;
/// AUD_ERROR_UNSUPPORTED where the Dart side asks (Android).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoSession>)>()
external int aud_io_session_permission(ffi.Pointer<AudIoSession> session);

/// [control] Asks the user for the microphone permission; the answer arrives
/// as AUD_IO_NOTIFY_PERMISSION. AUD_ERROR_UNSUPPORTED where the Dart side
/// asks.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoSession>)>()
external int aud_io_session_request_permission(
  ffi.Pointer<AudIoSession> session,
);

/// [control] Ends an interruption: streams that ran before start again and
/// report AUD_IO_NOTIFY_RESUMED.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoSession>)>()
external int aud_io_session_resume(ffi.Pointer<AudIoSession> session);

/// [control] Sets the listener the notification thread wakes; NULL removes
/// it. The notification thread has stopped calling the old listener when
/// the function returns.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudIoSession>,
    AudIoListener,
    ffi.Pointer<ffi.Void>,
  )
>()
external int aud_io_session_set_listener(
  ffi.Pointer<AudIoSession> session,
  AudIoListener listener,
  ffi.Pointer<ffi.Void> user,
);

/// [control] Takes the waiting notifications of the session and its
/// streams, at most `capacity`, in the order they happened; returns the
/// number taken.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudIoSession>,
    ffi.Pointer<AudIoNotification>,
    ffi.Uint32,
  )
>()
external int aud_io_session_take_notifications(
  ffi.Pointer<AudIoSession> session,
  ffi.Pointer<AudIoNotification> out,
  int capacity,
);

/// [realtime] Renders a 440 Hz sine at -20 dBFS into every output channel:
/// the smoke signal of the package. The phase follows the sample position,
/// so the function keeps no state; `user` is ignored.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<core.AudRenderRequest>)
>()
external int aud_io_sine_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<core.AudRenderRequest> request,
);

/// [control] Tells the stream that the render function is prepared for the
/// format of `generation`; the stream calls it again from the next block.
/// AUD_ERROR_STATE for a generation the stream does not have.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>, ffi.Uint32)>()
external int aud_io_stream_acknowledge(
  ffi.Pointer<AudIoStream> stream,
  int generation,
);

/// [control] Stops and closes the stream; no callback runs afterwards.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudIoStream>)>()
external void aud_io_stream_close(ffi.Pointer<AudIoStream> stream);

/// [control] Writes the counters into `out`.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudIoStream>, ffi.Pointer<AudIoCounters>)
>()
external int aud_io_stream_counters(
  ffi.Pointer<AudIoStream> stream,
  ffi.Pointer<AudIoCounters> out,
);

/// [control] Writes the format the stream got into `out`.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudIoStream>, ffi.Pointer<AudIoStreamFormat>)
>()
external int aud_io_stream_format(
  ffi.Pointer<AudIoStream> stream,
  ffi.Pointer<AudIoStreamFormat> out,
);

/// [control] The id that names the stream in notifications.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stream_id(ffi.Pointer<AudIoStream> stream);

/// [control] Opens a stream in the stopped state; NULL with the reason in
/// `result` (may be NULL), e.g. AUD_IO_ERROR_PERMISSION.
@ffi.Native<
  ffi.Pointer<AudIoStream> Function(
    ffi.Pointer<AudIoSession>,
    ffi.Pointer<AudIoStreamConfig>,
    ffi.Pointer<ffi.Int32>,
  )
>()
external ffi.Pointer<AudIoStream> aud_io_stream_open(
  ffi.Pointer<AudIoSession> session,
  ffi.Pointer<AudIoStreamConfig> config,
  ffi.Pointer<ffi.Int32> result,
);

/// [control] Zeroes the counters; the next period starts fresh.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stream_reset_counters(ffi.Pointer<AudIoStream> stream);

/// [control] Starts the callbacks; from the failed state it reopens first.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stream_start(ffi.Pointer<AudIoStream> stream);

/// [control] The AUD_IO_STATE_* of the stream.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stream_state(ffi.Pointer<AudIoStream> stream);

/// [control] Stops the callbacks; returns when no callback runs.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudIoStream>)>()
external int aud_io_stream_stop(ffi.Pointer<AudIoStream> stream);

/// [realtime] Copies the input into the output, channel by channel: a
/// monitor. The last input channel feeds the outputs beyond it, so a mono
/// input plays on every output channel. `user` is ignored.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<core.AudRenderRequest>)
>()
external int aud_io_thru_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<core.AudRenderRequest> request,
);

const int AUD_IO_API_VERSION = 2;

const int AUD_IO_BACKEND_NULL = 1;

const int AUD_IO_BACKEND_PLATFORM = 0;

const int AUD_IO_DEVICE_ACTIVE = 4;

const int AUD_IO_DEVICE_DEFAULT_INPUT = 2;

const int AUD_IO_DEVICE_DEFAULT_OUTPUT = 1;

const int AUD_IO_DUPLEX = 3;

const int AUD_IO_ERROR_DEVICE = -102;

const int AUD_IO_ERROR_INTERRUPTED = -103;

const int AUD_IO_ERROR_NO_DEVICE = -101;

const int AUD_IO_ERROR_PERMISSION = -100;

const int AUD_IO_FAULT_CHANNELS = 10;

const int AUD_IO_FAULT_DISCONNECT = 1;

const int AUD_IO_FAULT_FAIL_OPEN = 7;

const int AUD_IO_FAULT_FAIL_START = 11;

const int AUD_IO_FAULT_HOT_PLUG = 6;

const int AUD_IO_FAULT_INTERRUPT = 3;

const int AUD_IO_FAULT_LATE = 4;

const int AUD_IO_FAULT_PERMISSION = 8;

const int AUD_IO_FAULT_ROUTE = 9;

const int AUD_IO_FAULT_SAMPLE_RATE = 2;

const int AUD_IO_FAULT_XRUN = 5;

const int AUD_IO_INPUT = 2;

const int AUD_IO_MAX_CHANNELS = 32;

const int AUD_IO_MAX_ID = 128;

const int AUD_IO_MAX_NAME = 128;

const int AUD_IO_MAX_SAMPLE_RATES = 16;

const int AUD_IO_NOTIFY_DEVICES_CHANGED = 1;

const int AUD_IO_NOTIFY_DISCONNECTED = 4;

const int AUD_IO_NOTIFY_FAILED = 9;

const int AUD_IO_NOTIFY_FORMAT_CHANGED = 6;

const int AUD_IO_NOTIFY_INTERRUPTED = 7;

const int AUD_IO_NOTIFY_PERMISSION = 10;

const int AUD_IO_NOTIFY_RECOVERED = 12;

const int AUD_IO_NOTIFY_RENDER_ERROR = 11;

const int AUD_IO_NOTIFY_RESUMED = 8;

const int AUD_IO_NOTIFY_ROUTE_CHANGED = 5;

const int AUD_IO_NOTIFY_STARTED = 2;

const int AUD_IO_NOTIFY_STOPPED = 3;

const int AUD_IO_OUTPUT = 1;

const int AUD_IO_PERFORMANCE_LOW_LATENCY = 0;

const int AUD_IO_PERFORMANCE_NONE = 1;

const int AUD_IO_PERFORMANCE_POWER_SAVING = 2;

const int AUD_IO_PERMISSION_DENIED = 1;

const int AUD_IO_PERMISSION_GRANTED = 2;

const int AUD_IO_PERMISSION_UNDETERMINED = 0;

const int AUD_IO_REASON_APP_SUSPENDED = 5;

const int AUD_IO_REASON_BUILTIN_MIC_MUTED = 10;

const int AUD_IO_REASON_DEVICE_ADDED = 2;

const int AUD_IO_REASON_DEVICE_REMOVED = 1;

const int AUD_IO_REASON_ERROR = 9;

const int AUD_IO_REASON_FOCUS_LOSS = 6;

const int AUD_IO_REASON_MEDIA_SERVICES_RESET = 7;

const int AUD_IO_REASON_NONE = 0;

const int AUD_IO_REASON_REQUEST = 11;

const int AUD_IO_REASON_ROUTE_OVERRIDE = 3;

const int AUD_IO_REASON_SAMPLE_RATE = 8;

const int AUD_IO_REASON_SYSTEM = 4;

const int AUD_IO_ROUTE_AIRPLAY = 12;

const int AUD_IO_ROUTE_BLUETOOTH_A2DP = 8;

const int AUD_IO_ROUTE_BLUETOOTH_HFP = 9;

const int AUD_IO_ROUTE_BLUETOOTH_LE = 10;

const int AUD_IO_ROUTE_BUILTIN_MIC = 3;

const int AUD_IO_ROUTE_CAR = 13;

const int AUD_IO_ROUTE_HDMI = 11;

const int AUD_IO_ROUTE_HEARING_AID = 14;

const int AUD_IO_ROUTE_LINE = 6;

const int AUD_IO_ROUTE_RECEIVER = 2;

const int AUD_IO_ROUTE_SPEAKER = 1;

const int AUD_IO_ROUTE_UNKNOWN = 0;

const int AUD_IO_ROUTE_USB = 7;

const int AUD_IO_ROUTE_VIRTUAL = 15;

const int AUD_IO_ROUTE_WIRED_HEADPHONES = 4;

const int AUD_IO_ROUTE_WIRED_HEADSET = 5;

const int AUD_IO_SESSION_BLUETOOTH_HFP = 2;

const int AUD_IO_SESSION_MANUAL_CLOCK = 256;

const int AUD_IO_SESSION_MEASUREMENT = 4;

const int AUD_IO_SESSION_MIX_WITH_OTHERS = 1;

const int AUD_IO_STATE_FAILED = 4;

const int AUD_IO_STATE_INTERRUPTED = 3;

const int AUD_IO_STATE_RECOVERING = 2;

const int AUD_IO_STATE_RUNNING = 1;

const int AUD_IO_STATE_STOPPED = 0;

const int AUD_IO_STREAM_EXCLUSIVE = 1;

const int AUD_IO_STREAM_FOLLOW_FORMAT = 4;

const int AUD_IO_STREAM_LATENCY_TUNER = 2;

/// The counters of a stream since it opened or since the last reset.
final class AudIoCounters extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_IO_STATE_*
  @ffi.Uint32()
  external int state;

  /// device callbacks
  @ffi.Uint64()
  external int callbacks;

  /// frames of the device callbacks
  @ffi.Uint64()
  external int frames;

  /// render calls, after splitting
  @ffi.Uint64()
  external int renders;

  /// the smallest device callback
  @ffi.Uint32()
  external int callback_frames_min;

  /// the largest device callback
  @ffi.Uint32()
  external int callback_frames_max;

  /// between the starts of two callbacks
  @ffi.Int64()
  external int period_min_ns;

  @ffi.Int64()
  external int period_max_ns;

  @ffi.Int64()
  external int period_sum_ns;

  @ffi.Uint64()
  external int period_count;

  /// a period above 1.5 times the last block
  @ffi.Uint64()
  external int late_callbacks;

  /// underruns and overruns of the backend
  @ffi.Uint64()
  external int xruns;

  @ffi.Uint64()
  external int disconnects;

  /// the device reopened after a loss or a change
  @ffi.Uint64()
  external int recoveries;

  @ffi.Uint64()
  external int interruptions;

  /// silent while the client acknowledges
  @ffi.Uint64()
  external int held_blocks;

  /// the render function returned an error
  @ffi.Uint64()
  external int render_errors;

  @ffi.Uint64()
  external int notifications_dropped;

  /// spent inside the callback
  @ffi.Int64()
  external int callback_time_max_ns;

  @ffi.Int64()
  external int callback_time_sum_ns;

  /// from the loss to the first callback
  @ffi.Int64()
  external int recovery_time_max_ns;

  @ffi.Int64()
  external int recovery_time_last_ns;

  /// the largest timestamp deviation
  @ffi.Int64()
  external int host_time_jitter_max_ns;

  /// the time of the last block
  external core.AudStreamTime last_time;

  static ffi.Pointer<AudIoCounters> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int state,
    required int callbacks,
    required int frames,
    required int renders,
    required int callback_frames_min,
    required int callback_frames_max,
    required int period_min_ns,
    required int period_max_ns,
    required int period_sum_ns,
    required int period_count,
    required int late_callbacks,
    required int xruns,
    required int disconnects,
    required int recoveries,
    required int interruptions,
    required int held_blocks,
    required int render_errors,
    required int notifications_dropped,
    required int callback_time_max_ns,
    required int callback_time_sum_ns,
    required int recovery_time_max_ns,
    required int recovery_time_last_ns,
    required int host_time_jitter_max_ns,
    required core.AudStreamTime last_time,
  }) => $allocator<AudIoCounters>()
    ..ref.struct_size = struct_size
    ..ref.state = state
    ..ref.callbacks = callbacks
    ..ref.frames = frames
    ..ref.renders = renders
    ..ref.callback_frames_min = callback_frames_min
    ..ref.callback_frames_max = callback_frames_max
    ..ref.period_min_ns = period_min_ns
    ..ref.period_max_ns = period_max_ns
    ..ref.period_sum_ns = period_sum_ns
    ..ref.period_count = period_count
    ..ref.late_callbacks = late_callbacks
    ..ref.xruns = xruns
    ..ref.disconnects = disconnects
    ..ref.recoveries = recoveries
    ..ref.interruptions = interruptions
    ..ref.held_blocks = held_blocks
    ..ref.render_errors = render_errors
    ..ref.notifications_dropped = notifications_dropped
    ..ref.callback_time_max_ns = callback_time_max_ns
    ..ref.callback_time_sum_ns = callback_time_sum_ns
    ..ref.recovery_time_max_ns = recovery_time_max_ns
    ..ref.recovery_time_last_ns = recovery_time_last_ns
    ..ref.host_time_jitter_max_ns = host_time_jitter_max_ns
    ..ref.last_time = last_time;
}

/// An audio device. Ids are stable while the device is attached: the device
/// id of AudioManager on Android, the port UID on iOS.
final class AudIoDevice extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_IO_OUTPUT and AUD_IO_INPUT
  @ffi.Uint32()
  external int directions;

  /// AUD_IO_ROUTE_*
  @ffi.Uint32()
  external int route;

  /// AUD_IO_DEVICE_*
  @ffi.Uint32()
  external int flags;

  @ffi.Uint32()
  external int max_output_channels;

  @ffi.Uint32()
  external int max_input_channels;

  /// 0: any rate the backend converts to
  @ffi.Uint32()
  external int num_sample_rates;

  @ffi.Uint32()
  external int reserved;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Double> sample_rates;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> id;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;
}

/// Wakes the control thread: notifications wait. Called on the notification
/// thread, never on the realtime thread.
typedef AudIoListener = ffi.Pointer<ffi.NativeFunction<AudIoListenerFunction>>;
typedef AudIoListenerFunction = ffi.Void Function(ffi.Pointer<ffi.Void> user);
typedef DartAudIoListenerFunction = void Function(ffi.Pointer<ffi.Void> user);

final class AudIoNotification extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_IO_NOTIFY_*
  @ffi.Uint32()
  external int type;

  /// the stream id; 0 for the session
  @ffi.Int32()
  external int stream;

  /// a result code or AUD_IO_PERMISSION_*
  @ffi.Int32()
  external int code;

  /// AUD_IO_REASON_*
  @ffi.Uint32()
  external int reason;

  /// the stream's format generation afterwards
  @ffi.Uint32()
  external int generation;

  /// when it happened
  @ffi.Int64()
  external int host_time_ns;

  /// see the notification type
  @ffi.Int64()
  external int value;

  /// the stream's rate afterwards
  @ffi.Double()
  external double sample_rate;

  @ffi.Uint32()
  external int output_channels;

  @ffi.Uint32()
  external int input_channels;

  static ffi.Pointer<AudIoNotification> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int type,
    required int stream,
    required int code,
    required int reason,
    required int generation,
    required int host_time_ns,
    required int value,
    required double sample_rate,
    required int output_channels,
    required int input_channels,
  }) => $allocator<AudIoNotification>()
    ..ref.struct_size = struct_size
    ..ref.type = type
    ..ref.stream = stream
    ..ref.code = code
    ..ref.reason = reason
    ..ref.generation = generation
    ..ref.host_time_ns = host_time_ns
    ..ref.value = value
    ..ref.sample_rate = sample_rate
    ..ref.output_channels = output_channels
    ..ref.input_channels = input_channels;
}

/// The latency probe: plays a click - a 5 ms burst of 2 kHz - every interval
/// on every output channel and measures the time until its onset on the
/// first input channel, through a loop from the output to the input (a cable
/// or the air).
final class AudIoProbe extends ffi.Opaque {}

/// What a probe measured.
final class AudIoProbeResult extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// The largest absolute input sample so far: whether the input hears
  /// anything, and how loud the clicks come back.
  @ffi.Float()
  external double input_peak;

  /// clicks played
  @ffi.Int64()
  external int clicks;

  /// onsets found within an interval
  @ffi.Int64()
  external int detections;

  /// from the last click to its onset
  @ffi.Int64()
  external int last_round_trip_frames;

  @ffi.Int64()
  external int min_round_trip_frames;

  @ffi.Int64()
  external int max_round_trip_frames;

  @ffi.Int64()
  external int sum_round_trip_frames;

  /// The output plus the input latency the stream reported with the last
  /// detected click.
  @ffi.Int64()
  external int reported_round_trip_frames;

  static ffi.Pointer<AudIoProbeResult> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required double input_peak,
    required int clicks,
    required int detections,
    required int last_round_trip_frames,
    required int min_round_trip_frames,
    required int max_round_trip_frames,
    required int sum_round_trip_frames,
    required int reported_round_trip_frames,
  }) => $allocator<AudIoProbeResult>()
    ..ref.struct_size = struct_size
    ..ref.input_peak = input_peak
    ..ref.clicks = clicks
    ..ref.detections = detections
    ..ref.last_round_trip_frames = last_round_trip_frames
    ..ref.min_round_trip_frames = min_round_trip_frames
    ..ref.max_round_trip_frames = max_round_trip_frames
    ..ref.sum_round_trip_frames = sum_round_trip_frames
    ..ref.reported_round_trip_frames = reported_round_trip_frames;
}

final class AudIoSession extends ffi.Opaque {}

final class AudIoSessionConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_IO_BACKEND_*
  @ffi.Uint32()
  external int backend;

  /// what the app uses; iOS sets the category by it
  @ffi.Uint32()
  external int directions;

  /// AUD_IO_SESSION_*
  @ffi.Uint32()
  external int flags;

  /// 0 = 256
  @ffi.Uint32()
  external int notification_capacity;

  /// A recovery that has not reopened the device after this long gives up
  /// and reports AUD_IO_NOTIFY_FAILED; 0 = 5000.
  @ffi.Uint32()
  external int recovery_timeout_ms;

  static ffi.Pointer<AudIoSessionConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int backend,
    required int directions,
    required int flags,
    required int notification_capacity,
    required int recovery_timeout_ms,
  }) => $allocator<AudIoSessionConfig>()
    ..ref.struct_size = struct_size
    ..ref.backend = backend
    ..ref.directions = directions
    ..ref.flags = flags
    ..ref.notification_capacity = notification_capacity
    ..ref.recovery_timeout_ms = recovery_timeout_ms;
}

final class AudIoStream extends ffi.Opaque {}

/// What a stream asks for. A field left 0 takes the default.
final class AudIoStreamConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_IO_OUTPUT, AUD_IO_INPUT or AUD_IO_DUPLEX
  @ffi.Uint32()
  external int direction;

  /// NULL or "": the default output
  external ffi.Pointer<ffi.Char> output_device_id;

  /// NULL or "": the default input
  external ffi.Pointer<ffi.Char> input_device_id;

  /// 0: the route's channels, at most 2
  @ffi.Uint32()
  external int output_channels;

  /// 0: the route's channels, at most 2
  @ffi.Uint32()
  external int input_channels;

  /// 0: the device's rate, followed across route changes; a fixed rate is
  /// converted by the backend when the device runs at another one.
  @ffi.Double()
  external double sample_rate;

  /// the device buffer; 0: the low-latency default
  @ffi.Uint32()
  external int buffer_frames;

  /// the largest render block; 0 = 1024
  @ffi.Uint32()
  external int max_frames;

  /// AUD_IO_PERFORMANCE_*
  @ffi.Uint32()
  external int performance_mode;

  /// AUD_IO_STREAM_*
  @ffi.Uint32()
  external int flags;

  /// [realtime] called with every block
  external core.AudRenderFunction render;

  /// handed to render, e.g. an AudGraph
  external ffi.Pointer<ffi.Void> render_user;

  static ffi.Pointer<AudIoStreamConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int direction,
    required ffi.Pointer<ffi.Char> output_device_id,
    required ffi.Pointer<ffi.Char> input_device_id,
    required int output_channels,
    required int input_channels,
    required double sample_rate,
    required int buffer_frames,
    required int max_frames,
    required int performance_mode,
    required int flags,
    required core.AudRenderFunction render,
    required ffi.Pointer<ffi.Void> render_user,
  }) => $allocator<AudIoStreamConfig>()
    ..ref.struct_size = struct_size
    ..ref.direction = direction
    ..ref.output_device_id = output_device_id
    ..ref.input_device_id = input_device_id
    ..ref.output_channels = output_channels
    ..ref.input_channels = input_channels
    ..ref.sample_rate = sample_rate
    ..ref.buffer_frames = buffer_frames
    ..ref.max_frames = max_frames
    ..ref.performance_mode = performance_mode
    ..ref.flags = flags
    ..ref.render = render
    ..ref.render_user = render_user;
}

/// What a stream got. Changes with every notification that names a new
/// generation.
final class AudIoStreamFormat extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int direction;

  @ffi.Double()
  external double sample_rate;

  @ffi.Uint32()
  external int output_channels;

  @ffi.Uint32()
  external int input_channels;

  /// the largest render block
  @ffi.Uint32()
  external int max_frames;

  /// the device buffer
  @ffi.Uint32()
  external int buffer_frames;

  /// the device's period (Android: the burst)
  @ffi.Uint32()
  external int burst_frames;

  /// grows with every change of rate or channels
  @ffi.Uint32()
  external int generation;

  /// the granted AUD_IO_PERFORMANCE_*
  @ffi.Uint32()
  external int performance_mode;

  /// 1: exclusive sharing was granted
  @ffi.Uint32()
  external int exclusive;

  /// the AUD_TIME_SOURCE_* of the host times
  @ffi.Uint32()
  external int time_source;

  @ffi.Uint32()
  external int reserved;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> output_device_id;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> input_device_id;

  /// e.g. "oboe/aaudio", "miniaudio/Core Audio", "null"
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> backend;
}
