// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by scripts/generate-abi-constants.js from the ffigen bindings.
// Do not edit; run the script after ffigen.

// ignore_for_file: constant_identifier_names

const int AUD_IO_API_VERSION = 2;
const int AUD_IO_BACKEND_NULL = 1;
const int AUD_IO_BACKEND_PLATFORM = 0;
const int AUD_IO_DEVICE_ACTIVE = 4;
const int AUD_IO_DEVICE_DEFAULT_INPUT = 2;
const int AUD_IO_DEVICE_DEFAULT_OUTPUT = 1;
const int AUD_IO_DUPLEX = 3;
const int AUD_IO_ERROR_DEVICE = -102;
const int AUD_IO_ERROR_INTERRUPTED = -103;
const int AUD_IO_ERROR_NO_DEVICE = -101;
const int AUD_IO_ERROR_PERMISSION = -100;
const int AUD_IO_FAULT_CHANNELS = 10;
const int AUD_IO_FAULT_DISCONNECT = 1;
const int AUD_IO_FAULT_FAIL_OPEN = 7;
const int AUD_IO_FAULT_FAIL_START = 11;
const int AUD_IO_FAULT_HOT_PLUG = 6;
const int AUD_IO_FAULT_INTERRUPT = 3;
const int AUD_IO_FAULT_LATE = 4;
const int AUD_IO_FAULT_PERMISSION = 8;
const int AUD_IO_FAULT_ROUTE = 9;
const int AUD_IO_FAULT_SAMPLE_RATE = 2;
const int AUD_IO_FAULT_XRUN = 5;
const int AUD_IO_INPUT = 2;
const int AUD_IO_MAX_CHANNELS = 32;
const int AUD_IO_MAX_ID = 128;
const int AUD_IO_MAX_NAME = 128;
const int AUD_IO_MAX_SAMPLE_RATES = 16;
const int AUD_IO_NOTIFY_DEVICES_CHANGED = 1;
const int AUD_IO_NOTIFY_DISCONNECTED = 4;
const int AUD_IO_NOTIFY_FAILED = 9;
const int AUD_IO_NOTIFY_FORMAT_CHANGED = 6;
const int AUD_IO_NOTIFY_INTERRUPTED = 7;
const int AUD_IO_NOTIFY_PERMISSION = 10;
const int AUD_IO_NOTIFY_RECOVERED = 12;
const int AUD_IO_NOTIFY_RENDER_ERROR = 11;
const int AUD_IO_NOTIFY_RESUMED = 8;
const int AUD_IO_NOTIFY_ROUTE_CHANGED = 5;
const int AUD_IO_NOTIFY_STARTED = 2;
const int AUD_IO_NOTIFY_STOPPED = 3;
const int AUD_IO_OUTPUT = 1;
const int AUD_IO_PERFORMANCE_LOW_LATENCY = 0;
const int AUD_IO_PERFORMANCE_NONE = 1;
const int AUD_IO_PERFORMANCE_POWER_SAVING = 2;
const int AUD_IO_PERMISSION_DENIED = 1;
const int AUD_IO_PERMISSION_GRANTED = 2;
const int AUD_IO_PERMISSION_UNDETERMINED = 0;
const int AUD_IO_REASON_APP_SUSPENDED = 5;
const int AUD_IO_REASON_BUILTIN_MIC_MUTED = 10;
const int AUD_IO_REASON_DEVICE_ADDED = 2;
const int AUD_IO_REASON_DEVICE_REMOVED = 1;
const int AUD_IO_REASON_ERROR = 9;
const int AUD_IO_REASON_FOCUS_LOSS = 6;
const int AUD_IO_REASON_MEDIA_SERVICES_RESET = 7;
const int AUD_IO_REASON_NONE = 0;
const int AUD_IO_REASON_REQUEST = 11;
const int AUD_IO_REASON_ROUTE_OVERRIDE = 3;
const int AUD_IO_REASON_SAMPLE_RATE = 8;
const int AUD_IO_REASON_SYSTEM = 4;
const int AUD_IO_ROUTE_AIRPLAY = 12;
const int AUD_IO_ROUTE_BLUETOOTH_A2DP = 8;
const int AUD_IO_ROUTE_BLUETOOTH_HFP = 9;
const int AUD_IO_ROUTE_BLUETOOTH_LE = 10;
const int AUD_IO_ROUTE_BUILTIN_MIC = 3;
const int AUD_IO_ROUTE_CAR = 13;
const int AUD_IO_ROUTE_HDMI = 11;
const int AUD_IO_ROUTE_HEARING_AID = 14;
const int AUD_IO_ROUTE_LINE = 6;
const int AUD_IO_ROUTE_RECEIVER = 2;
const int AUD_IO_ROUTE_SPEAKER = 1;
const int AUD_IO_ROUTE_UNKNOWN = 0;
const int AUD_IO_ROUTE_USB = 7;
const int AUD_IO_ROUTE_VIRTUAL = 15;
const int AUD_IO_ROUTE_WIRED_HEADPHONES = 4;
const int AUD_IO_ROUTE_WIRED_HEADSET = 5;
const int AUD_IO_SESSION_BLUETOOTH_HFP = 2;
const int AUD_IO_SESSION_MANUAL_CLOCK = 256;
const int AUD_IO_SESSION_MEASUREMENT = 4;
const int AUD_IO_SESSION_MIX_WITH_OTHERS = 1;
const int AUD_IO_STATE_FAILED = 4;
const int AUD_IO_STATE_INTERRUPTED = 3;
const int AUD_IO_STATE_RECOVERING = 2;
const int AUD_IO_STATE_RUNNING = 1;
const int AUD_IO_STATE_STOPPED = 0;
const int AUD_IO_STREAM_EXCLUSIVE = 1;
const int AUD_IO_STREAM_FOLLOW_FORMAT = 4;
const int AUD_IO_STREAM_LATENCY_TUNER = 2;
