// AUTO GENERATED BY JNIGEN 1.0.1. DO NOT EDIT!

// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by jnigen through scripts/generate-android-bindings.js; it runs
// on Android only.
// coverage:ignore-file
// ignore_for_file: type=lint

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 1);

/// from: `android.content.Context`
extension type Context._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/content/Context');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Context> type = $Context$Type$();
  static final _id_AUDIO_SERVICE = _class.staticFieldId(
    r'AUDIO_SERVICE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String AUDIO_SERVICE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get AUDIO_SERVICE =>
      _id_AUDIO_SERVICE.getNullable(_class, jni$_.JString.type)
          as jni$_.JString?;
}

extension Context$$Methods on Context {
  static final _id_checkSelfPermission = Context._class.instanceMethodId(
    r'checkSelfPermission',
    r'(Ljava/lang/String;)I',
  );

  static final _checkSelfPermission =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract int checkSelfPermission(java.lang.String string)`
  core$_.int checkSelfPermission(jni$_.JString? string) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _checkSelfPermission(
      _$$selfRef.pointer,
      _id_checkSelfPermission.pointer,
      _$string.pointer,
    ).integer;
  }

  static final _id_getSystemService = Context._class.instanceMethodId(
    r'getSystemService',
    r'(Ljava/lang/Class;)Ljava/lang/Object;',
  );

  static final _getSystemService =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public final T getSystemService(java.lang.Class<T> class)`
  /// The returned object must be released after use, by calling the [release] method.
  $T? getSystemService<$T extends jni$_.JObject?>(jni$_.JClass? class$) {
    final _$$selfRef = reference;
    final _$class$ = class$?.reference ?? jni$_.jNullReference;
    return _getSystemService(
      _$$selfRef.pointer,
      _id_getSystemService.pointer,
      _$class$.pointer,
    ).object<$T?>();
  }

  static final _id_getSystemService$1 = Context._class.instanceMethodId(
    r'getSystemService',
    r'(Ljava/lang/String;)Ljava/lang/Object;',
  );

  static final _getSystemService$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public abstract java.lang.Object getSystemService(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getSystemService$1(jni$_.JString? string) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getSystemService$1(
      _$$selfRef.pointer,
      _id_getSystemService$1.pointer,
      _$string.pointer,
    ).object<jni$_.JObject?>();
  }
}

final class $Context$Type$ extends jni$_.JType<Context> {
  @jni$_.internal
  const $Context$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Context;';
}

/// from: `android.media.AudioManager$OnAudioFocusChangeListener`
extension type AudioManager$OnAudioFocusChangeListener._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/media/AudioManager$OnAudioFocusChangeListener',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioManager$OnAudioFocusChangeListener> type =
      $AudioManager$OnAudioFocusChangeListener$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $AudioManager$OnAudioFocusChangeListener>
  _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onAudioFocusChange(I)V') {
        _$impls[$p]!.onAudioFocusChange(
          ($a![0] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $AudioManager$OnAudioFocusChangeListener $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'android.media.AudioManager$OnAudioFocusChangeListener',
      $p,
      _$invokePointer,
      [if ($impl.onAudioFocusChange$async) r'onAudioFocusChange(I)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory AudioManager$OnAudioFocusChangeListener.implement(
    $AudioManager$OnAudioFocusChangeListener $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<AudioManager$OnAudioFocusChangeListener>();
  }
}

extension AudioManager$OnAudioFocusChangeListener$$Methods
    on AudioManager$OnAudioFocusChangeListener {
  static final _id_onAudioFocusChange = AudioManager$OnAudioFocusChangeListener
      ._class
      .instanceMethodId(r'onAudioFocusChange', r'(I)V');

  static final _onAudioFocusChange =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public abstract void onAudioFocusChange(int i)`
  void onAudioFocusChange(core$_.int i) {
    final _$$selfRef = reference;
    _onAudioFocusChange(
      _$$selfRef.pointer,
      _id_onAudioFocusChange.pointer,
      i,
    ).check();
  }
}

abstract base mixin class $AudioManager$OnAudioFocusChangeListener {
  factory $AudioManager$OnAudioFocusChangeListener({
    required void Function(core$_.int i) onAudioFocusChange,
    core$_.bool onAudioFocusChange$async,
  }) = _$AudioManager$OnAudioFocusChangeListener;

  void onAudioFocusChange(core$_.int i);
  core$_.bool get onAudioFocusChange$async => false;
}

final class _$AudioManager$OnAudioFocusChangeListener
    with $AudioManager$OnAudioFocusChangeListener {
  _$AudioManager$OnAudioFocusChangeListener({
    required void Function(core$_.int i) onAudioFocusChange,
    this.onAudioFocusChange$async = false,
  }) : _onAudioFocusChange = onAudioFocusChange;

  final void Function(core$_.int i) _onAudioFocusChange;
  final core$_.bool onAudioFocusChange$async;

  void onAudioFocusChange(core$_.int i) {
    return _onAudioFocusChange(i);
  }
}

final class $AudioManager$OnAudioFocusChangeListener$Type$
    extends jni$_.JType<AudioManager$OnAudioFocusChangeListener> {
  @jni$_.internal
  const $AudioManager$OnAudioFocusChangeListener$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Landroid/media/AudioManager$OnAudioFocusChangeListener;';
}

/// from: `android.media.AudioManager`
extension type AudioManager._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/media/AudioManager');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioManager> type = $AudioManager$Type$();

  /// from: `static public final int AUDIOFOCUS_GAIN`
  static const AUDIOFOCUS_GAIN = 1;

  /// from: `static public final int AUDIOFOCUS_LOSS`
  static const AUDIOFOCUS_LOSS = -1;

  /// from: `static public final int AUDIOFOCUS_LOSS_TRANSIENT`
  static const AUDIOFOCUS_LOSS_TRANSIENT = -2;

  /// from: `static public final int AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK`
  static const AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK = -3;

  /// from: `static public final int AUDIOFOCUS_REQUEST_DELAYED`
  static const AUDIOFOCUS_REQUEST_DELAYED = 2;

  /// from: `static public final int AUDIOFOCUS_REQUEST_GRANTED`
  static const AUDIOFOCUS_REQUEST_GRANTED = 1;

  /// from: `static public final int GET_DEVICES_ALL`
  static const GET_DEVICES_ALL = 3;
  static final _id_PROPERTY_OUTPUT_FRAMES_PER_BUFFER = _class.staticFieldId(
    r'PROPERTY_OUTPUT_FRAMES_PER_BUFFER',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PROPERTY_OUTPUT_FRAMES_PER_BUFFER`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get PROPERTY_OUTPUT_FRAMES_PER_BUFFER =>
      _id_PROPERTY_OUTPUT_FRAMES_PER_BUFFER.getNullable(
            _class,
            jni$_.JString.type,
          )
          as jni$_.JString?;

  static final _id_PROPERTY_OUTPUT_SAMPLE_RATE = _class.staticFieldId(
    r'PROPERTY_OUTPUT_SAMPLE_RATE',
    r'Ljava/lang/String;',
  );

  /// from: `static public final java.lang.String PROPERTY_OUTPUT_SAMPLE_RATE`
  /// The returned object must be released after use, by calling the [release] method.
  static jni$_.JString? get PROPERTY_OUTPUT_SAMPLE_RATE =>
      _id_PROPERTY_OUTPUT_SAMPLE_RATE.getNullable(_class, jni$_.JString.type)
          as jni$_.JString?;
}

extension AudioManager$$Methods on AudioManager {
  static final _id_abandonAudioFocusRequest = AudioManager._class
      .instanceMethodId(
        r'abandonAudioFocusRequest',
        r'(Landroid/media/AudioFocusRequest;)I',
      );

  static final _abandonAudioFocusRequest =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public int abandonAudioFocusRequest(android.media.AudioFocusRequest audioFocusRequest)`
  core$_.int abandonAudioFocusRequest(AudioFocusRequest? audioFocusRequest) {
    final _$$selfRef = reference;
    final _$audioFocusRequest =
        audioFocusRequest?.reference ?? jni$_.jNullReference;
    return _abandonAudioFocusRequest(
      _$$selfRef.pointer,
      _id_abandonAudioFocusRequest.pointer,
      _$audioFocusRequest.pointer,
    ).integer;
  }

  static final _id_getAudioDevicesForAttributes = AudioManager._class
      .instanceMethodId(
        r'getAudioDevicesForAttributes',
        r'(Landroid/media/AudioAttributes;)Ljava/util/List;',
      );

  static final _getAudioDevicesForAttributes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.util.List<android.media.AudioDeviceInfo> getAudioDevicesForAttributes(android.media.AudioAttributes audioAttributes)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JList<AudioDeviceInfo?>? getAudioDevicesForAttributes(
    AudioAttributes? audioAttributes,
  ) {
    final _$$selfRef = reference;
    final _$audioAttributes =
        audioAttributes?.reference ?? jni$_.jNullReference;
    return _getAudioDevicesForAttributes(
      _$$selfRef.pointer,
      _id_getAudioDevicesForAttributes.pointer,
      _$audioAttributes.pointer,
    ).object<jni$_.JList<AudioDeviceInfo?>?>();
  }

  static final _id_getDevices = AudioManager._class.instanceMethodId(
    r'getDevices',
    r'(I)[Landroid/media/AudioDeviceInfo;',
  );

  static final _getDevices =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.media.AudioDeviceInfo[] getDevices(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JArray<AudioDeviceInfo?>? getDevices(core$_.int i) {
    final _$$selfRef = reference;
    return _getDevices(
      _$$selfRef.pointer,
      _id_getDevices.pointer,
      i,
    ).object<jni$_.JArray<AudioDeviceInfo?>?>();
  }

  static final _id_getProperty = AudioManager._class.instanceMethodId(
    r'getProperty',
    r'(Ljava/lang/String;)Ljava/lang/String;',
  );

  static final _getProperty =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public java.lang.String getProperty(java.lang.String string)`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString? getProperty(jni$_.JString? string) {
    final _$$selfRef = reference;
    final _$string = string?.reference ?? jni$_.jNullReference;
    return _getProperty(
      _$$selfRef.pointer,
      _id_getProperty.pointer,
      _$string.pointer,
    ).object<jni$_.JString?>();
  }

  static final _id_requestAudioFocus = AudioManager._class.instanceMethodId(
    r'requestAudioFocus',
    r'(Landroid/media/AudioFocusRequest;)I',
  );

  static final _requestAudioFocus =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public int requestAudioFocus(android.media.AudioFocusRequest audioFocusRequest)`
  core$_.int requestAudioFocus(AudioFocusRequest? audioFocusRequest) {
    final _$$selfRef = reference;
    final _$audioFocusRequest =
        audioFocusRequest?.reference ?? jni$_.jNullReference;
    return _requestAudioFocus(
      _$$selfRef.pointer,
      _id_requestAudioFocus.pointer,
      _$audioFocusRequest.pointer,
    ).integer;
  }

  static final _id_requestAudioFocus$1 = AudioManager._class.instanceMethodId(
    r'requestAudioFocus',
    r'(Landroid/media/AudioManager$OnAudioFocusChangeListener;II)I',
  );

  static final _requestAudioFocus$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Int32, jni$_.Int32)
                >,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public int requestAudioFocus(android.media.AudioManager$OnAudioFocusChangeListener onAudioFocusChangeListener, int i, int i1)`
  @core$_.Deprecated('This Java method is deprecated.')
  core$_.int requestAudioFocus$1(
    AudioManager$OnAudioFocusChangeListener? onAudioFocusChangeListener,
    core$_.int i,
    core$_.int i1,
  ) {
    final _$$selfRef = reference;
    final _$onAudioFocusChangeListener =
        onAudioFocusChangeListener?.reference ?? jni$_.jNullReference;
    return _requestAudioFocus$1(
      _$$selfRef.pointer,
      _id_requestAudioFocus$1.pointer,
      _$onAudioFocusChangeListener.pointer,
      i,
      i1,
    ).integer;
  }
}

final class $AudioManager$Type$ extends jni$_.JType<AudioManager> {
  @jni$_.internal
  const $AudioManager$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioManager;';
}

/// from: `android.media.AudioDeviceInfo`
extension type AudioDeviceInfo._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/media/AudioDeviceInfo');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioDeviceInfo> type = $AudioDeviceInfo$Type$();

  /// from: `static public final int TYPE_AUX_LINE`
  static const TYPE_AUX_LINE = 19;

  /// from: `static public final int TYPE_BLE_BROADCAST`
  static const TYPE_BLE_BROADCAST = 30;

  /// from: `static public final int TYPE_BLE_HEADSET`
  static const TYPE_BLE_HEADSET = 26;

  /// from: `static public final int TYPE_BLE_SPEAKER`
  static const TYPE_BLE_SPEAKER = 27;

  /// from: `static public final int TYPE_BLUETOOTH_A2DP`
  static const TYPE_BLUETOOTH_A2DP = 8;

  /// from: `static public final int TYPE_BLUETOOTH_SCO`
  static const TYPE_BLUETOOTH_SCO = 7;

  /// from: `static public final int TYPE_BUILTIN_EARPIECE`
  static const TYPE_BUILTIN_EARPIECE = 1;

  /// from: `static public final int TYPE_BUILTIN_MIC`
  static const TYPE_BUILTIN_MIC = 15;

  /// from: `static public final int TYPE_BUILTIN_SPEAKER`
  static const TYPE_BUILTIN_SPEAKER = 2;

  /// from: `static public final int TYPE_BUILTIN_SPEAKER_SAFE`
  static const TYPE_BUILTIN_SPEAKER_SAFE = 24;

  /// from: `static public final int TYPE_BUS`
  static const TYPE_BUS = 21;

  /// from: `static public final int TYPE_DOCK`
  static const TYPE_DOCK = 13;

  /// from: `static public final int TYPE_DOCK_ANALOG`
  static const TYPE_DOCK_ANALOG = 31;

  /// from: `static public final int TYPE_FM`
  static const TYPE_FM = 14;

  /// from: `static public final int TYPE_FM_TUNER`
  static const TYPE_FM_TUNER = 16;

  /// from: `static public final int TYPE_HDMI`
  static const TYPE_HDMI = 9;

  /// from: `static public final int TYPE_HDMI_ARC`
  static const TYPE_HDMI_ARC = 10;

  /// from: `static public final int TYPE_HDMI_EARC`
  static const TYPE_HDMI_EARC = 29;

  /// from: `static public final int TYPE_HEARING_AID`
  static const TYPE_HEARING_AID = 23;

  /// from: `static public final int TYPE_IP`
  static const TYPE_IP = 20;

  /// from: `static public final int TYPE_LINE_ANALOG`
  static const TYPE_LINE_ANALOG = 5;

  /// from: `static public final int TYPE_LINE_DIGITAL`
  static const TYPE_LINE_DIGITAL = 6;

  /// from: `static public final int TYPE_MULTICHANNEL_GROUP`
  static const TYPE_MULTICHANNEL_GROUP = 32;

  /// from: `static public final int TYPE_REMOTE_SUBMIX`
  static const TYPE_REMOTE_SUBMIX = 25;

  /// from: `static public final int TYPE_TELEPHONY`
  static const TYPE_TELEPHONY = 18;

  /// from: `static public final int TYPE_TV_TUNER`
  static const TYPE_TV_TUNER = 17;

  /// from: `static public final int TYPE_UNKNOWN`
  static const TYPE_UNKNOWN = 0;

  /// from: `static public final int TYPE_USB_ACCESSORY`
  static const TYPE_USB_ACCESSORY = 12;

  /// from: `static public final int TYPE_USB_DEVICE`
  static const TYPE_USB_DEVICE = 11;

  /// from: `static public final int TYPE_USB_HEADSET`
  static const TYPE_USB_HEADSET = 22;

  /// from: `static public final int TYPE_WIRED_HEADPHONES`
  static const TYPE_WIRED_HEADPHONES = 4;

  /// from: `static public final int TYPE_WIRED_HEADSET`
  static const TYPE_WIRED_HEADSET = 3;
}

extension AudioDeviceInfo$$Methods on AudioDeviceInfo {
  static final _id_get$channelCounts = AudioDeviceInfo._class.instanceMethodId(
    r'getChannelCounts',
    r'()[I',
  );

  static final _get$channelCounts =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int[] getChannelCounts()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JIntArray? get channelCounts {
    final _$$selfRef = reference;
    return _get$channelCounts(
      _$$selfRef.pointer,
      _id_get$channelCounts.pointer,
    ).object<jni$_.JIntArray?>();
  }

  static final _id_get$id = AudioDeviceInfo._class.instanceMethodId(
    r'getId',
    r'()I',
  );

  static final _get$id =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getId()`
  core$_.int get id {
    final _$$selfRef = reference;
    return _get$id(_$$selfRef.pointer, _id_get$id.pointer).integer;
  }

  static final _id_get$productName = AudioDeviceInfo._class.instanceMethodId(
    r'getProductName',
    r'()Ljava/lang/CharSequence;',
  );

  static final _get$productName =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public java.lang.CharSequence getProductName()`
  /// The returned object must be released after use, by calling the [release] method.
  CharSequence? get productName {
    final _$$selfRef = reference;
    return _get$productName(
      _$$selfRef.pointer,
      _id_get$productName.pointer,
    ).object<CharSequence?>();
  }

  static final _id_get$sampleRates = AudioDeviceInfo._class.instanceMethodId(
    r'getSampleRates',
    r'()[I',
  );

  static final _get$sampleRates =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int[] getSampleRates()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JIntArray? get sampleRates {
    final _$$selfRef = reference;
    return _get$sampleRates(
      _$$selfRef.pointer,
      _id_get$sampleRates.pointer,
    ).object<jni$_.JIntArray?>();
  }

  static final _id_get$type$1 = AudioDeviceInfo._class.instanceMethodId(
    r'getType',
    r'()I',
  );

  static final _get$type$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public int getType()`
  core$_.int get type$1 {
    final _$$selfRef = reference;
    return _get$type$1(_$$selfRef.pointer, _id_get$type$1.pointer).integer;
  }

  static final _id_get$isSink = AudioDeviceInfo._class.instanceMethodId(
    r'isSink',
    r'()Z',
  );

  static final _get$isSink =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isSink()`
  core$_.bool get isSink {
    final _$$selfRef = reference;
    return _get$isSink(_$$selfRef.pointer, _id_get$isSink.pointer).boolean;
  }

  static final _id_get$isSource = AudioDeviceInfo._class.instanceMethodId(
    r'isSource',
    r'()Z',
  );

  static final _get$isSource =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public boolean isSource()`
  core$_.bool get isSource {
    final _$$selfRef = reference;
    return _get$isSource(_$$selfRef.pointer, _id_get$isSource.pointer).boolean;
  }
}

final class $AudioDeviceInfo$Type$ extends jni$_.JType<AudioDeviceInfo> {
  @jni$_.internal
  const $AudioDeviceInfo$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioDeviceInfo;';
}

/// from: `android.media.AudioFocusRequest$Builder`
extension type AudioFocusRequest$Builder._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/media/AudioFocusRequest$Builder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioFocusRequest$Builder> type =
      $AudioFocusRequest$Builder$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Landroid/media/AudioFocusRequest;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.media.AudioFocusRequest audioFocusRequest)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioFocusRequest$Builder(AudioFocusRequest? audioFocusRequest) {
    final _$$classRef = _class.reference;
    final _$audioFocusRequest =
        audioFocusRequest?.reference ?? jni$_.jNullReference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$audioFocusRequest.pointer,
    ).object<AudioFocusRequest$Builder>();
  }

  static final _id_new$1 = _class.constructorId(r'(I)V');

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioFocusRequest$Builder.new$1(core$_.int i) {
    final _$$classRef = _class.reference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      i,
    ).object<AudioFocusRequest$Builder>();
  }
}

extension AudioFocusRequest$Builder$$Methods on AudioFocusRequest$Builder {
  static final _id_build = AudioFocusRequest$Builder._class.instanceMethodId(
    r'build',
    r'()Landroid/media/AudioFocusRequest;',
  );

  static final _build =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.media.AudioFocusRequest build()`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest? build() {
    final _$$selfRef = reference;
    return _build(
      _$$selfRef.pointer,
      _id_build.pointer,
    ).object<AudioFocusRequest?>();
  }

  static final _id_setAcceptsDelayedFocusGain = AudioFocusRequest$Builder._class
      .instanceMethodId(
        r'setAcceptsDelayedFocusGain',
        r'(Z)Landroid/media/AudioFocusRequest$Builder;',
      );

  static final _setAcceptsDelayedFocusGain =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.media.AudioFocusRequest$Builder setAcceptsDelayedFocusGain(boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest$Builder? setAcceptsDelayedFocusGain(core$_.bool z) {
    final _$$selfRef = reference;
    return _setAcceptsDelayedFocusGain(
      _$$selfRef.pointer,
      _id_setAcceptsDelayedFocusGain.pointer,
      z ? 1 : 0,
    ).object<AudioFocusRequest$Builder?>();
  }

  static final _id_setAudioAttributes = AudioFocusRequest$Builder._class
      .instanceMethodId(
        r'setAudioAttributes',
        r'(Landroid/media/AudioAttributes;)Landroid/media/AudioFocusRequest$Builder;',
      );

  static final _setAudioAttributes =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.media.AudioFocusRequest$Builder setAudioAttributes(android.media.AudioAttributes audioAttributes)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest$Builder? setAudioAttributes(
    AudioAttributes? audioAttributes,
  ) {
    final _$$selfRef = reference;
    final _$audioAttributes =
        audioAttributes?.reference ?? jni$_.jNullReference;
    return _setAudioAttributes(
      _$$selfRef.pointer,
      _id_setAudioAttributes.pointer,
      _$audioAttributes.pointer,
    ).object<AudioFocusRequest$Builder?>();
  }

  static final _id_setOnAudioFocusChangeListener = AudioFocusRequest$Builder
      ._class
      .instanceMethodId(
        r'setOnAudioFocusChangeListener',
        r'(Landroid/media/AudioManager$OnAudioFocusChangeListener;)Landroid/media/AudioFocusRequest$Builder;',
      );

  static final _setOnAudioFocusChangeListener =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.media.AudioFocusRequest$Builder setOnAudioFocusChangeListener(android.media.AudioManager$OnAudioFocusChangeListener onAudioFocusChangeListener)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest$Builder? setOnAudioFocusChangeListener(
    AudioManager$OnAudioFocusChangeListener? onAudioFocusChangeListener,
  ) {
    final _$$selfRef = reference;
    final _$onAudioFocusChangeListener =
        onAudioFocusChangeListener?.reference ?? jni$_.jNullReference;
    return _setOnAudioFocusChangeListener(
      _$$selfRef.pointer,
      _id_setOnAudioFocusChangeListener.pointer,
      _$onAudioFocusChangeListener.pointer,
    ).object<AudioFocusRequest$Builder?>();
  }

  static final _id_setOnAudioFocusChangeListener$1 = AudioFocusRequest$Builder
      ._class
      .instanceMethodId(
        r'setOnAudioFocusChangeListener',
        r'(Landroid/media/AudioManager$OnAudioFocusChangeListener;Landroid/os/Handler;)Landroid/media/AudioFocusRequest$Builder;',
      );

  static final _setOnAudioFocusChangeListener$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public android.media.AudioFocusRequest$Builder setOnAudioFocusChangeListener(android.media.AudioManager$OnAudioFocusChangeListener onAudioFocusChangeListener, android.os.Handler handler)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest$Builder? setOnAudioFocusChangeListener$1(
    AudioManager$OnAudioFocusChangeListener? onAudioFocusChangeListener,
    Handler? handler,
  ) {
    final _$$selfRef = reference;
    final _$onAudioFocusChangeListener =
        onAudioFocusChangeListener?.reference ?? jni$_.jNullReference;
    final _$handler = handler?.reference ?? jni$_.jNullReference;
    return _setOnAudioFocusChangeListener$1(
      _$$selfRef.pointer,
      _id_setOnAudioFocusChangeListener$1.pointer,
      _$onAudioFocusChangeListener.pointer,
      _$handler.pointer,
    ).object<AudioFocusRequest$Builder?>();
  }

  static final _id_setWillPauseWhenDucked = AudioFocusRequest$Builder._class
      .instanceMethodId(
        r'setWillPauseWhenDucked',
        r'(Z)Landroid/media/AudioFocusRequest$Builder;',
      );

  static final _setWillPauseWhenDucked =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.media.AudioFocusRequest$Builder setWillPauseWhenDucked(boolean z)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioFocusRequest$Builder? setWillPauseWhenDucked(core$_.bool z) {
    final _$$selfRef = reference;
    return _setWillPauseWhenDucked(
      _$$selfRef.pointer,
      _id_setWillPauseWhenDucked.pointer,
      z ? 1 : 0,
    ).object<AudioFocusRequest$Builder?>();
  }
}

final class $AudioFocusRequest$Builder$Type$
    extends jni$_.JType<AudioFocusRequest$Builder> {
  @jni$_.internal
  const $AudioFocusRequest$Builder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioFocusRequest$Builder;';
}

/// from: `android.media.AudioFocusRequest`
extension type AudioFocusRequest._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/media/AudioFocusRequest',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioFocusRequest> type = $AudioFocusRequest$Type$();
}

final class $AudioFocusRequest$Type$ extends jni$_.JType<AudioFocusRequest> {
  @jni$_.internal
  const $AudioFocusRequest$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioFocusRequest;';
}

/// from: `android.media.AudioAttributes$Builder`
extension type AudioAttributes$Builder._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'android/media/AudioAttributes$Builder',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioAttributes$Builder> type =
      $AudioAttributes$Builder$Type$();
  static final _id_new$ = _class.constructorId(r'()V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioAttributes$Builder() {
    final _$$classRef = _class.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
    ).object<AudioAttributes$Builder>();
  }

  static final _id_new$1 = _class.constructorId(
    r'(Landroid/media/AudioAttributes;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.media.AudioAttributes audioAttributes)`
  /// The returned object must be released after use, by calling the [release] method.
  factory AudioAttributes$Builder.new$1(AudioAttributes? audioAttributes) {
    final _$$classRef = _class.reference;
    final _$audioAttributes =
        audioAttributes?.reference ?? jni$_.jNullReference;
    return _new$1(
      _$$classRef.pointer,
      _id_new$1.pointer,
      _$audioAttributes.pointer,
    ).object<AudioAttributes$Builder>();
  }
}

extension AudioAttributes$Builder$$Methods on AudioAttributes$Builder {
  static final _id_build = AudioAttributes$Builder._class.instanceMethodId(
    r'build',
    r'()Landroid/media/AudioAttributes;',
  );

  static final _build =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public android.media.AudioAttributes build()`
  /// The returned object must be released after use, by calling the [release] method.
  AudioAttributes? build() {
    final _$$selfRef = reference;
    return _build(
      _$$selfRef.pointer,
      _id_build.pointer,
    ).object<AudioAttributes?>();
  }

  static final _id_setContentType = AudioAttributes$Builder._class
      .instanceMethodId(
        r'setContentType',
        r'(I)Landroid/media/AudioAttributes$Builder;',
      );

  static final _setContentType =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.media.AudioAttributes$Builder setContentType(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioAttributes$Builder? setContentType(core$_.int i) {
    final _$$selfRef = reference;
    return _setContentType(
      _$$selfRef.pointer,
      _id_setContentType.pointer,
      i,
    ).object<AudioAttributes$Builder?>();
  }

  static final _id_setUsage = AudioAttributes$Builder._class.instanceMethodId(
    r'setUsage',
    r'(I)Landroid/media/AudioAttributes$Builder;',
  );

  static final _setUsage =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
            )
          >();

  /// from: `public android.media.AudioAttributes$Builder setUsage(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  AudioAttributes$Builder? setUsage(core$_.int i) {
    final _$$selfRef = reference;
    return _setUsage(
      _$$selfRef.pointer,
      _id_setUsage.pointer,
      i,
    ).object<AudioAttributes$Builder?>();
  }
}

final class $AudioAttributes$Builder$Type$
    extends jni$_.JType<AudioAttributes$Builder> {
  @jni$_.internal
  const $AudioAttributes$Builder$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioAttributes$Builder;';
}

/// from: `android.media.AudioAttributes`
extension type AudioAttributes._(jni$_.JObject _$this)
    implements jni$_.JObject, Parcelable {
  static final _class = jni$_.JClass.forName(r'android/media/AudioAttributes');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<AudioAttributes> type = $AudioAttributes$Type$();

  /// from: `static public final int CONTENT_TYPE_MUSIC`
  static const CONTENT_TYPE_MUSIC = 2;

  /// from: `static public final int USAGE_MEDIA`
  static const USAGE_MEDIA = 1;
}

final class $AudioAttributes$Type$ extends jni$_.JType<AudioAttributes> {
  @jni$_.internal
  const $AudioAttributes$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/media/AudioAttributes;';
}

/// from: `android.os.Build$VERSION`
extension type Build$VERSION._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/os/Build$VERSION');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build$VERSION> type = $Build$VERSION$Type$();
  static final _id_SDK_INT = _class.staticFieldId(r'SDK_INT', r'I');

  /// from: `static public final int SDK_INT`
  static core$_.int get SDK_INT =>
      _id_SDK_INT.getNullable(_class, jni$_.jint.type) as core$_.int;
}

final class $Build$VERSION$Type$ extends jni$_.JType<Build$VERSION> {
  @jni$_.internal
  const $Build$VERSION$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build$VERSION;';
}

/// from: `android.os.Build`
extension type Build._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(r'android/os/Build');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<Build> type = $Build$Type$();
}

final class $Build$Type$ extends jni$_.JType<Build> {
  @jni$_.internal
  const $Build$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Build;';
}

/// from: `java.lang.CharSequence`
///
/// WARNING: CharSequence is a stub. To generate bindings for this class, include
/// java.lang.CharSequence in your config's classes list.
///
extension type CharSequence._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<CharSequence> type = $CharSequence$Type$();
}

final class $CharSequence$Type$ extends jni$_.JType<CharSequence> {
  @jni$_.internal
  const $CharSequence$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Ljava/lang/CharSequence;';
}

/// from: `android.os.Handler`
///
/// WARNING: Handler is a stub. To generate bindings for this class, include
/// android.os.Handler in your config's classes list.
///
extension type Handler._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Handler> type = $Handler$Type$();
}

final class $Handler$Type$ extends jni$_.JType<Handler> {
  @jni$_.internal
  const $Handler$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Handler;';
}

/// from: `android.os.Parcelable`
///
/// WARNING: Parcelable is a stub. To generate bindings for this class, include
/// android.os.Parcelable in your config's classes list.
///
extension type Parcelable._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Parcelable> type = $Parcelable$Type$();
}

final class $Parcelable$Type$ extends jni$_.JType<Parcelable> {
  @jni$_.internal
  const $Parcelable$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/os/Parcelable;';
}
